In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
drivers = pd.read_csv("../data/raw/drivers.csv")
constructors = pd.read_csv("../data/raw/constructors.csv")
races = pd.read_csv("../data/raw/races.csv")
results = pd.read_csv("../data/raw/results.csv")
qualifying = pd.read_csv("../data/raw/qualifying.csv")
circuits = pd.read_csv("../data/raw/circuits.csv")

In [3]:
drivers.head()

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [ ]:
#Drivers
drivers.shape

(861, 9)

In [6]:
drivers.info()

<class 'pandas.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     861 non-null    int64
 1   driverRef    861 non-null    str
 2   number       861 non-null    str
 3   code         861 non-null    str
 4   forename     861 non-null    str
 5   surname      861 non-null    str
 6   dob          861 non-null    str
 7   nationality  861 non-null    str
 8   url          861 non-null    str
dtypes: int64(1), str(8)
memory usage: 60.7 KB

In [7]:
drivers.describe()

         driverId
count  861.000000
mean   431.061556
std    248.793797
min      1.000000
25%    216.000000
50%    431.000000
75%    646.000000
max    862.000000

In [18]:
def explore_data(df, name):
    print("=" * 80)
    print(f"Dataset: {name}")
    print("=" * 80)

    print("\nShape:")
    print(df.shape)

    print("\nColumns:")
    print(df.columns)

    print("\nInfo:")
    df.info()

    print("\nMissing Values:")
    print(df.isnull().sum())

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\nSummary Statistics:")
    print("Numerical Columns")
    display(df.describe())

    print("\nCategorical Columns")
    display(df.describe(include='object'))

    print("\n\n")

In [19]:
explore_data(drivers, "Drivers")

explore_data(constructors, "Constructors")

explore_data(races, "Races")

explore_data(results, "Results")

explore_data(qualifying, "Qualifying")

explore_data(circuits, "Circuits")

================================================================================
Dataset: Drivers
================================================================================

Shape:
(861, 9)

Columns:
Index(['driverId', 'driverRef', 'number', 'code', 'forename', 'surname', 'dob',
       'nationality', 'url'],
      dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 861 entries, 0 to 860
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   driverId     861 non-null    int64
 1   driverRef    861 non-null    str
 2   number       861 non-null    str
 3   code         861 non-null    str
 4   forename     861 non-null    str
 5   surname      861 non-null    str
 6   dob          861 non-null    str
 7   nationality  861 non-null    str
 8   url          861 non-null    str
dtypes: int64(1), str(8)
memory usage: 60.7 KB

Missing Values:
driverId       0
driverRef      0
number         0
code           0
forename       0
surname        0
dob            0
nationality    0
url            0
dtype: int64

First 5 Rows:

,driverId,driverRef,number,code,forename,surname,dob,nationality,url
0,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

Summary Statistics:
Numerical Columns

         driverId
count  861.000000
mean   431.061556
std    248.793797
min      1.000000
25%    216.000000
50%    431.000000
75%    646.000000
max    862.000000

Categorical Columns

C:\Users\srisu\AppData\Local\Temp\ipykernel_17548\2610664818.py:26: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,driverRef,number,code,forename,surname,dob,nationality,url
count,861,861,861,861,861,861,861,861
unique,861,49,98,478,802,843,43,861
top,hamilton,\N,\N,John,Taylor,1950-01-18,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
freq,1,802,757,14,5,2,166,1

================================================================================
Dataset: Constructors
================================================================================

Shape:
(212, 5)

Columns:
Index(['constructorId', 'constructorRef', 'name', 'nationality', 'url'], dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 212 entries, 0 to 211
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   constructorId   212 non-null    int64
 1   constructorRef  212 non-null    str
 2   name            212 non-null    str
 3   nationality     212 non-null    str
 4   url             212 non-null    str
dtypes: int64(1), str(4)
memory usage: 8.4 KB

Missing Values:
constructorId     0
constructorRef    0
name              0
nationality       0
url               0
dtype: int64

First 5 Rows:

,constructorId,constructorRef,name,nationality,url
0,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,toro_rosso,Toro Rosso,Italian,http://en.wikipedia.org/wiki/Scuderia_Toro_Rosso

Summary Statistics:
Numerical Columns

       constructorId
count     212.000000
mean      107.547170
std        61.952685
min         1.000000
25%        54.750000
50%       107.500000
75%       160.250000
max       215.000000

Categorical Columns

C:\Users\srisu\AppData\Local\Temp\ipykernel_17548\2610664818.py:26: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,constructorRef,name,nationality,url
count,212,212,212,212
unique,212,212,24,175
top,mclaren,McLaren,British,http://en.wikipedia.org/wiki/Cooper_Car_Company
freq,1,1,86,11

================================================================================
Dataset: Races
================================================================================

Shape:
(1125, 18)

Columns:
Index(['raceId', 'year', 'round', 'circuitId', 'name', 'date', 'time', 'url',
       'fp1_date', 'fp1_time', 'fp2_date', 'fp2_time', 'fp3_date', 'fp3_time',
       'quali_date', 'quali_time', 'sprint_date', 'sprint_time'],
      dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 1125 entries, 0 to 1124
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   raceId       1125 non-null   int64
 1   year         1125 non-null   int64
 2   round        1125 non-null   int64
 3   circuitId    1125 non-null   int64
 4   name         1125 non-null   str
 5   date         1125 non-null   str
 6   time         1125 non-null   str
 7   url          1125 non-null   str
 8   fp1_date     1125 non-null   str
 9   fp1_time     1125 non-null   str
 10  fp2_date     1125 non-null   str
 11  fp2_time     1125 non-null   str
 12  fp3_date     1125 non-null   str
 13  fp3_time     1125 non-null   str
 14  quali_date   1125 non-null   str
 15  quali_time   1125 non-null   str
 16  sprint_date  1125 non-null   str
 17  sprint_time  1125 non-null   str
dtypes: int64(4), str(14)
memory usage: 158.3 KB

Missing Values:
raceId         0
year           0
round          0
circuitId      0
name           0
date           0
time           0
url            0
fp1_date       0
fp1_time       0
fp2_date       0
fp2_time       0
fp3_date       0
fp3_time       0
quali_date     0
quali_time     0
sprint_date    0
sprint_time    0
dtype: int64

First 5 Rows:

,raceId,year,round,circuitId,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,2009,1,1,Australian Grand Prix,2009-03-29,06:00:00,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,2009,2,2,Malaysian Grand Prix,2009-04-05,09:00:00,http://en.wikipedia.org/wiki/2009_Malaysian_Gr...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,2009,3,17,Chinese Grand Prix,2009-04-19,07:00:00,http://en.wikipedia.org/wiki/2009_Chinese_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,2009,4,3,Bahrain Grand Prix,2009-04-26,12:00:00,http://en.wikipedia.org/wiki/2009_Bahrain_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,2009,5,4,Spanish Grand Prix,2009-05-10,12:00:00,http://en.wikipedia.org/wiki/2009_Spanish_Gran...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

Summary Statistics:
Numerical Columns

            raceId         year        round    circuitId
count  1125.000000  1125.000000  1125.000000  1125.000000
mean    565.710222  1992.703111     8.579556    23.889778
std     328.813817    20.603848     5.159910    19.633527
min       1.000000  1950.000000     1.000000     1.000000
25%     282.000000  1977.000000     4.000000     9.000000
50%     563.000000  1994.000000     8.000000    18.000000
75%     845.000000  2011.000000    13.000000    34.000000
max    1144.000000  2024.000000    24.000000    80.000000

Categorical Columns

C:\Users\srisu\AppData\Local\Temp\ipykernel_17548\2610664818.py:26: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,name,date,time,url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
count,1125,1125,1125,1125,1125,1125,1125,1125,1125,1125,1125,1125,1125,1125
unique,54,1125,35,1125,91,21,91,20,73,19,91,16,19,13
top,British Grand Prix,2009-03-29,\N,http://en.wikipedia.org/wiki/2009_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
freq,75,1,731,1,1035,1057,1035,1057,1053,1072,1035,1057,1107,1110

================================================================================
Dataset: Results
================================================================================

Shape:
(26759, 18)

Columns:
Index(['resultId', 'raceId', 'driverId', 'constructorId', 'number', 'grid',
       'position', 'positionText', 'positionOrder', 'points', 'laps', 'time',
       'milliseconds', 'fastestLap', 'rank', 'fastestLapTime',
       'fastestLapSpeed', 'statusId'],
      dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   resultId         26759 non-null  int64
 1   raceId           26759 non-null  int64
 2   driverId         26759 non-null  int64
 3   constructorId    26759 non-null  int64
 4   number           26759 non-null  str
 5   grid             26759 non-null  int64
 6   position         26759 non-null  str
 7   positionText     26759 non-null  str
 8   positionOrder    26759 non-null  int64
 9   points           26759 non-null  float64
 10  laps             26759 non-null  int64
 11  time             26759 non-null  str
 12  milliseconds     26759 non-null  str
 13  fastestLap       26759 non-null  str
 14  rank             26759 non-null  str
 15  fastestLapTime   26759 non-null  str
 16  fastestLapSpeed  26759 non-null  str
 17  statusId         26759 non-null  int64
dtypes: float64(1), int64(8), str(9)
memory usage: 3.7 MB

Missing Values:
resultId           0
raceId             0
driverId           0
constructorId      0
number             0
grid               0
position           0
positionText       0
positionOrder      0
points             0
laps               0
time               0
milliseconds       0
fastestLap         0
rank               0
fastestLapTime     0
fastestLapSpeed    0
statusId           0
dtype: int64

First 5 Rows:

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1

Summary Statistics:
Numerical Columns

,resultId,raceId,driverId,constructorId,grid,positionOrder,points,laps,statusId
count,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000,26759.000000
mean,13380.977391,551.687283,278.673530,50.180537,11.134796,12.794051,1.987632,46.301768,17.224971
std,7726.134642,313.265036,282.703039,61.551498,7.202860,7.665951,4.351209,29.496557,26.026104
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,1.000000
25%,6690.500000,300.000000,57.000000,6.000000,5.000000,6.000000,0.000000,23.000000,1.000000
50%,13380.000000,531.000000,172.000000,25.000000,11.000000,12.000000,0.000000,53.000000,10.000000
75%,20069.500000,811.000000,399.500000,63.000000,17.000000,18.000000,2.000000,66.000000,14.000000
max,26764.000000,1144.000000,862.000000,215.000000,34.000000,39.000000,50.000000,200.000000,141.000000

Categorical Columns

C:\Users\srisu\AppData\Local\Temp\ipykernel_17548\2610664818.py:26: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,number,position,positionText,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed
count,26759,26759,26759,26759,26759,26759,26759,26759,26759
unique,130,34,39,7411,7639,81,26,7474,7725
top,4,\N,R,\N,\N,\N,\N,\N,\N
freq,1019,10953,8897,19079,19079,18507,18249,18507,18507

================================================================================
Dataset: Qualifying
================================================================================

Shape:
(10494, 9)

Columns:
Index(['qualifyId', 'raceId', 'driverId', 'constructorId', 'number',
       'position', 'q1', 'q2', 'q3'],
      dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 10494 entries, 0 to 10493
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   qualifyId      10494 non-null  int64
 1   raceId         10494 non-null  int64
 2   driverId       10494 non-null  int64
 3   constructorId  10494 non-null  int64
 4   number         10494 non-null  int64
 5   position       10494 non-null  int64
 6   q1             10494 non-null  str
 7   q2             10472 non-null  str
 8   q3             10448 non-null  str
dtypes: int64(6), str(3)
memory usage: 738.0 KB

Missing Values:
qualifyId         0
raceId            0
driverId          0
constructorId     0
number            0
position          0
q1                0
q2               22
q3               46
dtype: int64

First 5 Rows:

,qualifyId,raceId,driverId,constructorId,number,position,q1,q2,q3
0,1,18,1,1,22,1,1:26.572,1:25.187,1:26.714
1,2,18,9,2,4,2,1:26.103,1:25.315,1:26.869
2,3,18,5,1,23,3,1:25.664,1:25.452,1:27.079
3,4,18,13,6,2,4,1:25.994,1:25.691,1:27.178
4,5,18,2,2,3,5,1:25.960,1:25.518,1:27.236

Summary Statistics:
Numerical Columns

,qualifyId,raceId,driverId,constructorId,number,position
count,10494.000000,10494.000000,10494.000000,10494.000000,10494.000000,10494.000000
mean,5262.482847,624.600915,343.002287,47.918430,18.786449,11.195826
std,3046.588486,428.298147,389.586448,73.217993,18.447502,6.260374
min,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000
25%,2625.250000,160.000000,17.000000,4.000000,7.000000,6.000000
50%,5249.500000,870.000000,60.000000,9.000000,14.000000,11.000000
75%,7893.750000,1006.000000,822.000000,31.000000,22.000000,16.000000
max,10551.000000,1144.000000,862.000000,215.000000,99.000000,28.000000

Categorical Columns

C:\Users\srisu\AppData\Local\Temp\ipykernel_17548\2610664818.py:26: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

           q1     q2     q3
count   10494  10472  10448
unique   9147   5474   3471
top        \N     \N     \N
freq      156   4625   6819

================================================================================
Dataset: Circuits
================================================================================

Shape:
(77, 9)

Columns:
Index(['circuitId', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng',
       'alt', 'url'],
      dtype='str')

Info:
<class 'pandas.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   circuitId   77 non-null     int64
 1   circuitRef  77 non-null     str
 2   name        77 non-null     str
 3   location    77 non-null     str
 4   country     77 non-null     str
 5   lat         77 non-null     float64
 6   lng         77 non-null     float64
 7   alt         77 non-null     int64
 8   url         77 non-null     str
dtypes: float64(2), int64(2), str(5)
memory usage: 5.5 KB

Missing Values:
circuitId     0
circuitRef    0
name          0
location      0
country       0
lat           0
lng           0
alt           0
url           0
dtype: int64

First 5 Rows:

,circuitId,circuitRef,name,location,country,lat,lng,alt,url
0,1,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.84970,144.96800,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,sepang,Sepang International Circuit,Kuala Lumpur,Malaysia,2.76083,101.73800,18,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,3,bahrain,Bahrain International Circuit,Sakhir,Bahrain,26.03250,50.51060,7,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,4,catalunya,Circuit de Barcelona-Catalunya,Montmeló,Spain,41.57000,2.26111,109,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,5,istanbul,Istanbul Park,Istanbul,Turkey,40.95170,29.40500,130,http://en.wikipedia.org/wiki/Istanbul_Park

Summary Statistics:
Numerical Columns

       circuitId        lat         lng          alt
count  77.000000  77.000000   77.000000    77.000000
mean   39.883117  33.442925    1.076683   247.012987
std    23.001701  22.808866   65.516951   362.738469
min     1.000000 -37.849700 -118.189000    -7.000000
25%    20.000000  32.777400   -9.394170    18.000000
50%    40.000000  40.951700    3.930830   129.000000
75%    59.000000  46.958900   19.248600   332.000000
max    80.000000  57.265300  144.968000  2227.000000

Categorical Columns

C:\Users\srisu\AppData\Local\Temp\ipykernel_17548\2610664818.py:26: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  display(df.describe(include='object'))

,circuitRef,name,location,country,url
count,77,77,77,77,77
unique,77,77,75,35,77
top,albert_park,Albert Park Grand Prix Circuit,California,USA,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
freq,1,1,2,11,1

In [20]:
print("Drivers PK Unique:", drivers["driverId"].is_unique)
print("Constructors PK Unique:", constructors["constructorId"].is_unique)
print("Races PK Unique:", races["raceId"].is_unique)
print("Circuits PK Unique:", circuits["circuitId"].is_unique)
print("Results PK Unique:", results["resultId"].is_unique)
print("Qualifying PK Unique:", qualifying["qualifyId"].is_unique)

Drivers PK Unique: True
Constructors PK Unique: True
Races PK Unique: True
Circuits PK Unique: True
Results PK Unique: True
Qualifying PK Unique: True

In [21]:
results_drivers = pd.merge(
    results,
    drivers,
    on="driverId",
    how="left"
)

results_drivers.head()

,resultId,raceId,driverId,constructorId,number_x,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,driverRef,number_y,code,forename,surname,dob,nationality,url
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,hamilton,44,HAM,Lewis,Hamilton,1985-01-07,British,http://en.wikipedia.org/wiki/Lewis_Hamilton
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,heidfeld,\N,HEI,Nick,Heidfeld,1977-05-10,German,http://en.wikipedia.org/wiki/Nick_Heidfeld
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,rosberg,6,ROS,Nico,Rosberg,1985-06-27,German,http://en.wikipedia.org/wiki/Nico_Rosberg
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,alonso,14,ALO,Fernando,Alonso,1981-07-29,Spanish,http://en.wikipedia.org/wiki/Fernando_Alonso
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,kovalainen,\N,KOV,Heikki,Kovalainen,1981-10-19,Finnish,http://en.wikipedia.org/wiki/Heikki_Kovalainen

In [22]:
print("Before Merge :", results.shape)
print("After Merge  :", results_drivers.shape)

Before Merge : (26759, 18)
After Merge  : (26759, 26)

In [28]:
df = results.copy()
df = pd.merge(
    df,
    constructors,
    on="constructorId",
    how="left",
)

df.head()

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,constructorRef,name,nationality,url
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren

In [29]:
print(df.shape)

(26759, 22)

In [30]:
df = pd.merge(
    df,
    races,
    on="raceId",
    how="left"
)

print(df.shape)
df.head()

(26759, 39)

,resultId,raceId,driverId,constructorId,number,grid,position,positionText,positionOrder,points,laps,time_x,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,constructorRef,name_x,nationality,url_x,year,round,circuitId,name_y,date,time_y,url_y,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N

In [34]:
df.columns.tolist()

['resultId',
 'raceId',
 'driverId',
 'constructorId',
 'number',
 'grid',
 'position',
 'positionText',
 'positionOrder',
 'points',
 'laps',
 'time_x',
 'milliseconds',
 'fastestLap',
 'rank',
 'fastestLapTime',
 'fastestLapSpeed',
 'statusId',
 'constructorRef',
 'name_x',
 'nationality',
 'url_x',
 'year',
 'round',
 'circuitId',
 'name_y',
 'date',
 'time_y',
 'url_y',
 'fp1_date',
 'fp1_time',
 'fp2_date',
 'fp2_time',
 'fp3_date',
 'fp3_time',
 'quali_date',
 'quali_time',
 'sprint_date',
 'sprint_time']

In [35]:
df.filter(regex="(_x|_y)$").columns

Index(['time_x', 'name_x', 'url_x', 'name_y', 'time_y', 'url_y'], dtype='str')

In [37]:
df.rename(columns={
    "name_x": "constructor_name",
    "name_y": "race_name",
    "url_x": "constructor_url",
    "url_y": "race_url",
    "time_x": "finish_time",
    "time_y": "race_time"
}, inplace=True)

In [38]:
df = pd.merge(
    df,
    qualifying,
    on=["raceId", "driverId", "constructorId"],
    how="left"
)

print(df.shape)

(26759, 45)

In [39]:
df = pd.merge(
    df,
    circuits,
    on="circuitId",
    how="left"
)

print(df.shape)

(26759, 53)

In [40]:
df.filter(regex="(_x|_y)$").columns

Index(['number_x', 'position_x', 'number_y', 'position_y'], dtype='str')

In [41]:
df.rename(columns={
    "number_x": "car_number",
    "position_x": "race_position",
    "position_y": "qualifying_position"
}, inplace=True)

In [42]:
df.drop(columns="number_y", inplace=True)

In [44]:
df.filter(regex="(_x|_y)$").columns

Index([], dtype='str')

In [45]:
print(df.shape)

df.head()

(26759, 52)

,resultId,raceId,driverId,constructorId,car_number,grid,race_position,positionText,positionOrder,points,laps,finish_time,milliseconds,fastestLap,rank,fastestLapTime,fastestLapSpeed,statusId,constructorRef,constructor_name,nationality,constructor_url,year,round,circuitId,race_name,date,race_time,race_url,fp1_date,fp1_time,fp2_date,fp2_time,fp3_date,fp3_time,quali_date,quali_time,sprint_date,sprint_time,qualifyId,qualifying_position,q1,q2,q3,circuitRef,name,location,country,lat,lng,alt,url
0,1,18,1,1,22,1,1,1,1,10.0,58,1:34:50.616,5690616,39,2,1:27.452,218.300,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,1.0,1.0,1:26.572,1:25.187,1:26.714,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
1,2,18,2,2,3,5,2,2,2,8.0,58,+5.478,5696094,41,3,1:27.739,217.586,1,bmw_sauber,BMW Sauber,German,http://en.wikipedia.org/wiki/BMW_Sauber,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,5.0,5.0,1:25.960,1:25.518,1:27.236,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
2,3,18,3,3,7,7,3,3,3,6.0,58,+8.163,5698779,41,5,1:28.090,216.719,1,williams,Williams,British,http://en.wikipedia.org/wiki/Williams_Grand_Pr...,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,7.0,7.0,1:26.295,1:26.059,1:28.687,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
3,4,18,4,4,5,11,4,4,4,5.0,58,+17.181,5707797,58,7,1:28.603,215.464,1,renault,Renault,French,http://en.wikipedia.org/wiki/Renault_in_Formul...,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,12.0,12.0,1:26.907,1:26.188,\N,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...
4,5,18,5,1,23,3,5,5,5,4.0,58,+18.014,5708630,43,1,1:27.418,218.385,1,mclaren,McLaren,British,http://en.wikipedia.org/wiki/McLaren,2008,1,1,Australian Grand Prix,2008-03-16,04:30:00,http://en.wikipedia.org/wiki/2008_Australian_G...,\N,\N,\N,\N,\N,\N,\N,\N,\N,\N,3.0,3.0,1:25.664,1:25.452,1:27.079,albert_park,Albert Park Grand Prix Circuit,Melbourne,Australia,-37.8497,144.968,10,http://en.wikipedia.org/wiki/Melbourne_Grand_P...

In [46]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26759 entries, 0 to 26758
Data columns (total 52 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   resultId             26759 non-null  int64
 1   raceId               26759 non-null  int64
 2   driverId             26759 non-null  int64
 3   constructorId        26759 non-null  int64
 4   car_number           26759 non-null  str
 5   grid                 26759 non-null  int64
 6   race_position        26759 non-null  str
 7   positionText         26759 non-null  str
 8   positionOrder        26759 non-null  int64
 9   points               26759 non-null  float64
 10  laps                 26759 non-null  int64
 11  finish_time          26759 non-null  str
 12  milliseconds         26759 non-null  str
 13  fastestLap           26759 non-null  str
 14  rank                 26759 non-null  str
 15  fastestLapTime       26759 non-null  str
 16  fastestLapSpeed      26759 non-null  str
 17  statusId             26759 non-null  int64
 18  constructorRef       26759 non-null  str
 19  constructor_name     26759 non-null  str
 20  nationality          26759 non-null  str
 21  constructor_url      26759 non-null  str
 22  year                 26759 non-null  int64
 23  round                26759 non-null  int64
 24  circuitId            26759 non-null  int64
 25  race_name            26759 non-null  str
 26  date                 26759 non-null  str
 27  race_time            26759 non-null  str
 28  race_url             26759 non-null  str
 29  fp1_date             26759 non-null  str
 30  fp1_time             26759 non-null  str
 31  fp2_date             26759 non-null  str
 32  fp2_time             26759 non-null  str
 33  fp3_date             26759 non-null  str
 34  fp3_time             26759 non-null  str
 35  quali_date           26759 non-null  str
 36  quali_time           26759 non-null  str
 37  sprint_date          26759 non-null  str
 38  sprint_time          26759 non-null  str
 39  qualifyId            10484 non-null  float64
 40  qualifying_position  10484 non-null  float64
 41  q1                   10484 non-null  str
 42  q2                   10462 non-null  str
 43  q3                   10438 non-null  str
 44  circuitRef           26759 non-null  str
 45  name                 26759 non-null  str
 46  location             26759 non-null  str
 47  country              26759 non-null  str
 48  lat                  26759 non-null  float64
 49  lng                  26759 non-null  float64
 50  alt                  26759 non-null  int64
 51  url                  26759 non-null  str
dtypes: float64(5), int64(12), str(35)
memory usage: 10.6 MB

In [50]:
df.isnull().sum()

resultId                   0
raceId                     0
driverId                   0
constructorId              0
car_number                 0
grid                       0
race_position              0
positionText               0
positionOrder              0
points                     0
laps                       0
finish_time                0
milliseconds               0
fastestLap                 0
rank                       0
fastestLapTime             0
fastestLapSpeed            0
statusId                   0
constructorRef             0
constructor_name           0
nationality                0
constructor_url            0
year                       0
round                      0
circuitId                  0
race_name                  0
date                       0
race_time                  0
race_url                   0
fp1_date                   0
fp1_time                   0
fp2_date                   0
fp2_time                   0
fp3_date                   0
fp3_time                   0
quali_date                 0
quali_time                 0
sprint_date                0
sprint_time                0
qualifyId              16275
qualifying_position    16275
q1                     16275
q2                     16297
q3                     16321
circuitRef                 0
name                       0
location                   0
country                    0
lat                        0
lng                        0
alt                        0
url                        0
dtype: int64

In [51]:
df.isnull().sum().sort_values(ascending=False)

q3                     16321
q2                     16297
qualifyId              16275
q1                     16275
qualifying_position    16275
car_number                 0
race_position              0
grid                       0
positionOrder              0
points                     0
laps                       0
finish_time                0
milliseconds               0
fastestLap                 0
rank                       0
positionText               0
resultId                   0
raceId                     0
driverId                   0
constructorId              0
constructor_name           0
constructorRef             0
statusId                   0
fastestLapSpeed            0
fastestLapTime             0
nationality                0
year                       0
constructor_url            0
race_url                   0
fp1_date                   0
fp1_time                   0
round                      0
circuitId                  0
race_name                  0
date                       0
race_time                  0
quali_date                 0
fp3_time                   0
fp3_date                   0
fp2_time                   0
fp2_date                   0
sprint_time                0
quali_time                 0
sprint_date                0
circuitRef                 0
name                       0
location                   0
country                    0
lat                        0
lng                        0
alt                        0
url                        0
dtype: int64

In [52]:
missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage.sort_values(ascending=False)

q3                     60.992563
q2                     60.902874
qualifyId              60.820658
q1                     60.820658
qualifying_position    60.820658
car_number              0.000000
race_position           0.000000
grid                    0.000000
positionOrder           0.000000
points                  0.000000
laps                    0.000000
finish_time             0.000000
milliseconds            0.000000
fastestLap              0.000000
rank                    0.000000
positionText            0.000000
resultId                0.000000
raceId                  0.000000
driverId                0.000000
constructorId           0.000000
constructor_name        0.000000
constructorRef          0.000000
statusId                0.000000
fastestLapSpeed         0.000000
fastestLapTime          0.000000
nationality             0.000000
year                    0.000000
constructor_url         0.000000
race_url                0.000000
fp1_date                0.000000
fp1_time                0.000000
round                   0.000000
circuitId               0.000000
race_name               0.000000
date                    0.000000
race_time               0.000000
quali_date              0.000000
fp3_time                0.000000
fp3_date                0.000000
fp2_time                0.000000
fp2_date                0.000000
sprint_time             0.000000
quali_time              0.000000
sprint_date             0.000000
circuitRef              0.000000
name                    0.000000
location                0.000000
country                 0.000000
lat                     0.000000
lng                     0.000000
alt                     0.000000
url                     0.000000
dtype: float64

In [53]:
df["Top10"] = (df["positionOrder"] <= 10).astype(int)

In [54]:
df[["positionOrder", "Top10"]].head(15)

    positionOrder  Top10
0               1      1
1               2      1
2               3      1
3               4      1
4               5      1
5               6      1
6               7      1
7               8      1
8               9      1
9              10      1
10             11      0
11             12      0
12             13      0
13             14      0
14             15      0

In [57]:
df["Top10"].value_counts()

Top10
0    15438
1    11321
Name: count, dtype: int64

In [58]:
df["Top10"].value_counts(normalize=True) * 100

Top10
0    57.692739
1    42.307261
Name: proportion, dtype: float64

In [59]:


model_df = df.copy()

In [60]:
leakage_columns = [
    "race_position",
    "positionOrder",
    "positionText",
    "points",
    "finish_time",
    "milliseconds",
    "fastestLap",
    "fastestLapTime",
    "fastestLapSpeed",
    "rank"
]

model_df.drop(columns=leakage_columns, inplace=True)

In [61]:
model_df.shape

(26759, 43)

In [62]:
model_df.columns.tolist()

['resultId',
 'raceId',
 'driverId',
 'constructorId',
 'car_number',
 'grid',
 'laps',
 'statusId',
 'constructorRef',
 'constructor_name',
 'nationality',
 'constructor_url',
 'year',
 'round',
 'circuitId',
 'race_name',
 'date',
 'race_time',
 'race_url',
 'fp1_date',
 'fp1_time',
 'fp2_date',
 'fp2_time',
 'fp3_date',
 'fp3_time',
 'quali_date',
 'quali_time',
 'sprint_date',
 'sprint_time',
 'qualifyId',
 'qualifying_position',
 'q1',
 'q2',
 'q3',
 'circuitRef',
 'name',
 'location',
 'country',
 'lat',
 'lng',
 'alt',
 'url',
 'Top10']

In [63]:
id_columns = [
    "resultId",
    "raceId",
    "driverId",
    "constructorId",
    "circuitId",
    "qualifyId"
]

model_df.drop(columns=id_columns, inplace=True, errors="ignore")

In [64]:
url_columns = [
    "url",
    "constructor_url",
    "race_url"
]

model_df.drop(columns=url_columns, inplace=True, errors="ignore")

In [65]:
practice_columns = [
    "fp1_date",
    "fp1_time",
    "fp2_date",
    "fp2_time",
    "fp3_date",
    "fp3_time"
]

model_df.drop(columns=practice_columns, inplace=True, errors="ignore")

In [66]:
qualifying_time_columns = [
    "q1",
    "q2",
    "q3"
]

model_df.drop(columns=qualifying_time_columns, inplace=True, errors="ignore")

In [67]:
print(model_df.shape)
print(model_df.columns.tolist())

(26759, 25)
['car_number', 'grid', 'laps', 'statusId', 'constructorRef', 'constructor_name', 'nationality', 'year', 'round', 'race_name', 'date', 'race_time', 'quali_date', 'quali_time', 'sprint_date', 'sprint_time', 'qualifying_position', 'circuitRef', 'name', 'location', 'country', 'lat', 'lng', 'alt', 'Top10']

In [68]:
columns_to_drop = [
    "laps",
    "statusId",
    "race_time",
    "quali_date",
    "quali_time",
    "sprint_date",
    "sprint_time"
]

model_df.drop(columns=columns_to_drop, inplace=True)

In [69]:
model_df.drop(columns=["constructorRef"], inplace=True)